from .cnn._classifier import CNNClassifier
from .cnn._regressor import CNNRegressor
from .encoder._classifier import EncoderClassifier
from .encoder._regressor import EncoderRegressor
from .fcn._classifier import FCNClassifier
from .fcn._regressor import FCNRegressor
from .mcdcnn._classifier import MCDCNNClassifier
from .mcnn._classifier import MCNNClassifier
from .mlp._classifier import MLPClassifier
from .mlp._regressor import MLPRegressor
from .resnet._classifier import ResNetClassifier
from .resnet._regressor import ResNetRegressor
from .tlenet._classifier import TLENETClassifier
from .tlenet._regressor import TLENETRegressor
from .twiesn._classifier import TWIESNClassifier
from .inceptiontime._classifier import InceptionTimeClassifier
from .inceptiontime._regressor import InceptionTimeRegressor
from .rnn._regressor import SimpleRNNRegressor
from .lstm._regressor import LSTMRegressor
